linters:
  enable:
  - gofmt
  - revive
  - misspell
  - dupl
  - unused
  - gosec
  - gocritic

issues:
 exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
